#!/bin/sh
[ "${IPKG_NO_SCRIPT}" = "1" ] && exit 0
[ -s ${IPKG_INSTROOT}/lib/functions.sh ] || exit 0
. ${IPKG_INSTROOT}/lib/functions.sh
default_postinst $0 $@
. /etc/profile.d/opkg.sh
if ! uci -q show opkg.auto > /dev/null 2>&1; then opkg init; fi


